// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Nakohartum/practicum-metrics/internal/config/db (interfaces: DatabaseAdapter)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Nakohartum/practicum-metrics/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockDatabaseAdapter is a mock of DatabaseAdapter interface.
type MockDatabaseAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseAdapterMockRecorder
}

// MockDatabaseAdapterMockRecorder is the mock recorder for MockDatabaseAdapter.
type MockDatabaseAdapterMockRecorder struct {
	mock *MockDatabaseAdapter
}

// NewMockDatabaseAdapter creates a new mock instance.
func NewMockDatabaseAdapter(ctrl *gomock.Controller) *MockDatabaseAdapter {
	mock := &MockDatabaseAdapter{ctrl: ctrl}
	mock.recorder = &MockDatabaseAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseAdapter) EXPECT() *MockDatabaseAdapterMockRecorder {
	return m.recorder
}

// CheckConnection mocks base method.
func (m *MockDatabaseAdapter) CheckConnection(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConnection", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckConnection indicates an expected call of CheckConnection.
func (mr *MockDatabaseAdapterMockRecorder) CheckConnection(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConnection", reflect.TypeOf((*MockDatabaseAdapter)(nil).CheckConnection), arg0)
}

// Close mocks base method.
func (m *MockDatabaseAdapter) Close(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaseAdapterMockRecorder) Close(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabaseAdapter)(nil).Close), arg0)
}

// GetAll mocks base method.
func (m *MockDatabaseAdapter) GetAll() []models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Metrics)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDatabaseAdapterMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDatabaseAdapter)(nil).GetAll))
}

// GetData mocks base method.
func (m *MockDatabaseAdapter) GetData(arg0, arg1 string) (models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", arg0, arg1)
	ret0, _ := ret[0].(models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockDatabaseAdapterMockRecorder) GetData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockDatabaseAdapter)(nil).GetData), arg0, arg1)
}

// Open mocks base method.
func (m *MockDatabaseAdapter) Open(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockDatabaseAdapterMockRecorder) Open(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockDatabaseAdapter)(nil).Open), arg0)
}

// SetData mocks base method.
func (m *MockDatabaseAdapter) SetData(arg0 models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetData indicates an expected call of SetData.
func (mr *MockDatabaseAdapterMockRecorder) SetData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetData", reflect.TypeOf((*MockDatabaseAdapter)(nil).SetData), arg0)
}
