// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/fileworkerinterface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Nakohartum/practicum-metrics/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockFileWorker is a mock of FileWorker interface.
type MockFileWorker struct {
	ctrl     *gomock.Controller
	recorder *MockFileWorkerMockRecorder
}

// MockFileWorkerMockRecorder is the mock recorder for MockFileWorker.
type MockFileWorkerMockRecorder struct {
	mock *MockFileWorker
}

// NewMockFileWorker creates a new mock instance.
func NewMockFileWorker(ctrl *gomock.Controller) *MockFileWorker {
	mock := &MockFileWorker{ctrl: ctrl}
	mock.recorder = &MockFileWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileWorker) EXPECT() *MockFileWorkerMockRecorder {
	return m.recorder
}

// FileExists mocks base method.
func (m *MockFileWorker) FileExists() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists")
	ret0, _ := ret[0].(error)
	return ret0
}

// FileExists indicates an expected call of FileExists.
func (mr *MockFileWorkerMockRecorder) FileExists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockFileWorker)(nil).FileExists))
}

// ReadData mocks base method.
func (m *MockFileWorker) ReadData() ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadData")
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadData indicates an expected call of ReadData.
func (mr *MockFileWorkerMockRecorder) ReadData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadData", reflect.TypeOf((*MockFileWorker)(nil).ReadData))
}

// WriteData mocks base method.
func (m *MockFileWorker) WriteData(data []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteData", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteData indicates an expected call of WriteData.
func (mr *MockFileWorkerMockRecorder) WriteData(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteData", reflect.TypeOf((*MockFileWorker)(nil).WriteData), data)
}

// WriteOneData mocks base method.
func (m *MockFileWorker) WriteOneData(data models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteOneData", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteOneData indicates an expected call of WriteOneData.
func (mr *MockFileWorkerMockRecorder) WriteOneData(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteOneData", reflect.TypeOf((*MockFileWorker)(nil).WriteOneData), data)
}
