// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Nakohartum/practicum-metrics/internal/service (interfaces: Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Nakohartum/practicum-metrics/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockService) GetAll() []models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Metrics)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockService)(nil).GetAll))
}

// GetData mocks base method.
func (m *MockService) GetData(arg0, arg1 string) (models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", arg0, arg1)
	ret0, _ := ret[0].(models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockServiceMockRecorder) GetData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockService)(nil).GetData), arg0, arg1)
}

// Ping mocks base method.
func (m *MockService) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockServiceMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockService)(nil).Ping), arg0)
}

// RunSaving mocks base method.
func (m *MockService) RunSaving(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RunSaving", arg0)
}

// RunSaving indicates an expected call of RunSaving.
func (mr *MockServiceMockRecorder) RunSaving(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSaving", reflect.TypeOf((*MockService)(nil).RunSaving), arg0)
}

// SaveAllData mocks base method.
func (m *MockService) SaveAllData() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAllData")
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAllData indicates an expected call of SaveAllData.
func (mr *MockServiceMockRecorder) SaveAllData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAllData", reflect.TypeOf((*MockService)(nil).SaveAllData))
}

// SaveDataAfterExit mocks base method.
func (m *MockService) SaveDataAfterExit(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDataAfterExit", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDataAfterExit indicates an expected call of SaveDataAfterExit.
func (mr *MockServiceMockRecorder) SaveDataAfterExit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDataAfterExit", reflect.TypeOf((*MockService)(nil).SaveDataAfterExit), arg0)
}

// SetData mocks base method.
func (m *MockService) SetData(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetData indicates an expected call of SetData.
func (mr *MockServiceMockRecorder) SetData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetData", reflect.TypeOf((*MockService)(nil).SetData), arg0, arg1, arg2)
}
