package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/types"
	"log"
	"os"
	"path/filepath"

	"golang.org/x/tools/go/packages"
)

type targetStruct struct {
	name  string
	named *types.Named
}

func main() {
	cfg := &packages.Config{
		Mode: packages.LoadSyntax,
		Dir:  ".",
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		log.Fatal(err)
	}

	if packages.PrintErrors(pkgs) > 0 {
		log.Fatal("there were errors loading packages")
	}

	for _, pkg := range pkgs {
		targets := findTargetStructs(pkg)
		if len(targets) == 0 {
			continue
		}

		src, err := generatePackageFile(pkg.Name, targets)
		if err != nil {
			log.Fatal(err)
		}

		outPath := filepath.Join(filepath.Dir(pkg.GoFiles[0]), "reset.gen.go")
		if err := os.WriteFile(outPath, src, 0o644); err != nil {
			log.Fatal(err)
		}
	}
}

func findTargetStructs(pkg *packages.Package) []targetStruct {
	var targets []targetStruct

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Doc == nil || !hasResetComment(genDecl.Doc) {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				if _, ok := typeSpec.Type.(*ast.StructType); !ok {
					continue
				}

				obj, ok := pkg.TypesInfo.Defs[typeSpec.Name].(*types.TypeName)
				if !ok {
					continue
				}

				named, ok := obj.Type().(*types.Named)
				if !ok {
					continue
				}

				targets = append(targets, targetStruct{
					name:  typeSpec.Name.Name,
					named: named,
				})
			}
		}
	}

	return targets
}

func generatePackageFile(packageName string, targets []targetStruct) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintln(&buf, "// Code generated by cmd/reset; DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "package %s\n\n", packageName)

	for _, target := range targets {
		fmt.Fprintf(&buf, "func (s *%s) Reset() {\n", target.name)

		structType, ok := target.named.Underlying().(*types.Struct)
		if !ok {
			continue
		}

		for i := 0; i < structType.NumFields(); i++ {
			field := structType.Field(i)
			if !field.Exported() && field.Pkg() != target.named.Obj().Pkg() {
				continue
			}

			writeResetCode(&buf, "s."+field.Name(), field.Type(), "\t")
		}

		fmt.Fprintln(&buf, "}")
		fmt.Fprintln(&buf)
	}

	return format.Source(buf.Bytes())
}

func writeResetCode(buf *bytes.Buffer, expr string, typ types.Type, indent string) {
	switch t := typ.(type) {
	case *types.Pointer:
		if named, ok := t.Elem().(*types.Named); ok && isStruct(named) && hasResetMethod(t) {
			fmt.Fprintf(buf, "%sif %s != nil {\n", indent, expr)
			fmt.Fprintf(buf, "%s\t%s.Reset()\n", indent, expr)
			fmt.Fprintf(buf, "%s}\n", indent)
			return
		}

		fmt.Fprintf(buf, "%sif %s != nil {\n", indent, expr)
		writeResetCode(buf, "*"+expr, t.Elem(), indent+"\t")
		fmt.Fprintf(buf, "%s}\n", indent)

	case *types.Slice:
		fmt.Fprintf(buf, "%s%s = %s[:0]\n", indent, expr, expr)

	case *types.Map:
		fmt.Fprintf(buf, "%sclear(%s)\n", indent, expr)

	case *types.Named:
		if isStruct(t) && hasResetMethod(types.NewPointer(t)) {
			fmt.Fprintf(buf, "%s%s.Reset()\n", indent, expr)
			return
		}
		writeResetCode(buf, expr, t.Underlying(), indent)

	case *types.Basic:
		switch {
		case t.Info()&types.IsBoolean != 0:
			fmt.Fprintf(buf, "%s%s = false\n", indent, expr)
		case t.Info()&types.IsString != 0:
			fmt.Fprintf(buf, "%s%s = \"\"\n", indent, expr)
		case t.Info()&(types.IsInteger|types.IsFloat|types.IsComplex) != 0:
			fmt.Fprintf(buf, "%s%s = 0\n", indent, expr)
		}
	}
}

func hasResetComment(doc *ast.CommentGroup) bool {
	for _, comment := range doc.List {
		if comment.Text == "// generate:reset" {
			return true
		}
	}
	return false
}

func isStruct(named *types.Named) bool {
	_, ok := named.Underlying().(*types.Struct)
	return ok
}

func hasResetMethod(typ types.Type) bool {
	methodSet := types.NewMethodSet(typ)
	selection := methodSet.Lookup(nil, "Reset")
	if selection == nil {
		return false
	}

	sig, ok := selection.Obj().Type().(*types.Signature)
	if !ok {
		return false
	}

	return sig.Params().Len() == 0 && sig.Results().Len() == 0
}
